// Beautify Africa — General Beauty E-Commerce Catalog & Mobile Content Data

export const MOCK_CATEGORIES = [
  { id: 'all', name: 'All Products', icon: 'sparkles' },
  { id: 'Skincare', name: 'Skincare', icon: 'water' },
  { id: 'Makeup', name: 'Makeup', icon: 'color-palette' },
  { id: 'Hair Care', name: 'Hair Care', icon: 'cut' },
  { id: 'Fragrance', name: 'Fragrance', icon: 'flask' },
  { id: 'Bath & Body', name: 'Bath & Body', icon: 'happy' },
  { id: 'Tools & Brushes', name: 'Tools & Accessories', icon: 'brush' },
  { id: 'Grooming', name: 'Grooming', icon: 'person' },
];

export const MOCK_PRODUCTS = [
  {
    _id: '650000000000000000000001',
    id: 1,
    name: 'Velvet Matte Liquid Lipstick',
    slug: 'velvet-matte-liquid-lipstick',
    brand: 'Beautify Cosmetics',
    category: 'Makeup',
    subcategory: 'Lipsticks',
    price: 18.00,
    originalPrice: 24.00,
    rating: 4.8,
    numReviews: 210,
    inStock: true,
    stockCount: 85,
    isBestSeller: true,
    isNewProduct: false,
    image: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?q=80&w=1200&auto=format&fit=crop',
      'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'A long-wearing, smudge-proof matte liquid lipstick that glides on smoothly for high-pigment, comfortable weightless color all day.',
    skinType: ['All Skin Types'],
    ingredients: 'Isododecane, Dimethicone, Trimethylsiloxysilicate, Polypropylsilsesquioxane, Tocopheryl Acetate (Vitamin E), Iron Oxides, Titanium Dioxide.',
    howToUse: 'Apply evenly onto clean, dry lips using the precision applicator tip. Allow 30 seconds to set to a transfer-resistant matte finish.',
    origin: 'Pan-African Beauty Hub',
    reviews: [
      { id: 'r1', user: 'Zuri M.', rating: 5, comment: 'Stays on all day through lunch and drinks! Love the pigment.', date: '2026-08-14' },
      { id: 'r2', user: 'Amina K.', rating: 5, comment: 'Super comfortable formula. Doesn’t dry out my lips.', date: '2026-08-08' }
    ]
  },
  {
    _id: '650000000000000000000002',
    id: 2,
    name: 'Hydrating Hyaluronic Acid Serum',
    slug: 'hydrating-hyaluronic-acid-serum',
    brand: 'GlowLab Skincare',
    category: 'Skincare',
    subcategory: 'Serums',
    price: 26.00,
    originalPrice: 32.00,
    rating: 4.9,
    numReviews: 185,
    inStock: true,
    stockCount: 60,
    isBestSeller: true,
    isNewProduct: false,
    image: 'https://images.unsplash.com/photo-1627384113743-6bd5a479fffd?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1627384113743-6bd5a479fffd?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1608248597359-299f1c7d2c38?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'An ultra-hydrating daily facial serum powered by 2% multi-molecular weight Hyaluronic Acid and Vitamin B5 to plump, soothe, and lock in moisture.',
    skinType: ['Dry', 'Normal', 'Combination', 'Sensitive'],
    ingredients: 'Aqua (Water), Sodium Hyaluronate, Panthenol (Vitamin B5), Glycerin, Sodium Crosspolymer, Ethylhexylglycerin, Phenoxyethanol.',
    howToUse: 'Apply 3-4 drops to clean, damp face and neck morning and evening. Follow with your favorite moisturizer.',
    origin: 'Formulated for All Climates',
    reviews: []
  },
  {
    _id: '650000000000000000000003',
    id: 3,
    name: 'Shea Butter Nourishing Body Cream',
    slug: 'shea-butter-nourishing-body-cream',
    brand: 'Pure Radiance',
    category: 'Bath & Body',
    subcategory: 'Body Lotions',
    price: 22.00,
    originalPrice: null,
    rating: 4.9,
    numReviews: 144,
    inStock: true,
    stockCount: 75,
    isBestSeller: true,
    isNewProduct: false,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'A rich, fast-absorbing body moisturizer enriched with natural African Shea Butter and Cocoa Butter to repair dry skin and provide 48-hour continuous hydration.',
    skinType: ['Dry', 'Normal', 'Very Dry'],
    ingredients: 'Aqua, Butyrospermum Parkii (Shea) Butter, Theobroma Cacao (Cocoa) Seed Butter, Cetearyl Alcohol, Glycerin, Tocopherol (Vitamin E).',
    howToUse: 'Massage generously all over the body after showering or whenever skin feels dry.',
    origin: 'Ghana & West Africa',
    reviews: []
  },
  {
    _id: '650000000000000000000004',
    id: 4,
    name: 'Pro Precision Makeup Sponge Set',
    slug: 'pro-precision-makeup-sponge-set',
    brand: 'Beautify Studio',
    category: 'Tools & Brushes',
    subcategory: 'Sponges',
    price: 14.00,
    originalPrice: 18.00,
    rating: 4.7,
    numReviews: 98,
    inStock: true,
    stockCount: 120,
    isBestSeller: false,
    isNewProduct: true,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdd403ea2?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdd403ea2?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'A set of 3 latex-free beauty blending sponges designed for seamless application of liquids, creams, and powders with streak-free coverage.',
    skinType: ['All Skin Types'],
    ingredients: '100% Latex-Free Hydrophilic Polyurethane Foam.',
    howToUse: 'Wet sponge thoroughly and squeeze out excess water. Bounce gently on skin to blend foundation, concealer, or powder.',
    origin: 'Professional Studio Tools',
    reviews: []
  },
  {
    _id: '650000000000000000000005',
    id: 5,
    name: 'Amber & Sweet Vanilla Eau de Parfum',
    slug: 'amber-sweet-vanilla-eau-de-parfum',
    brand: 'Maison de Parfum',
    category: 'Fragrance',
    subcategory: 'Perfume',
    price: 55.00,
    originalPrice: 65.00,
    rating: 4.9,
    numReviews: 112,
    inStock: true,
    stockCount: 35,
    isBestSeller: true,
    isNewProduct: false,
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'A warm, seductive fragrance featuring notes of golden amber, Madagascar vanilla, soft jasmine, and sandalwood. Long-lasting scent for day or evening.',
    skinType: ['All'],
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Benzyl Salicylate, Coumarin, Linalool, Limonene.',
    howToUse: 'Spray onto pulse points such as wrists, neck, and behind ears for optimal scent longevity.',
    origin: 'Fine Fragrance Collection',
    reviews: []
  },
  {
    _id: '650000000000000000000006',
    id: 6,
    name: 'Castor & Rosemary Scalp Oil Treatment',
    slug: 'castor-rosemary-scalp-oil-treatment',
    brand: 'AfriHair Essentials',
    category: 'Hair Care',
    subcategory: 'Hair Oils',
    price: 20.00,
    originalPrice: 25.00,
    rating: 4.8,
    numReviews: 165,
    inStock: true,
    stockCount: 90,
    isBestSeller: true,
    isNewProduct: false,
    image: 'https://images.unsplash.com/photo-1608248547160-fbc763c01566?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1608248547160-fbc763c01566?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'A potent hair and scalp oil formulated with Jamaican Black Castor Oil, Rosemary extract, and Argan oil to promote strong, thick, and healthy hair growth.',
    skinType: ['All Hair Types', 'Coily', 'Curly', 'Textured'],
    ingredients: 'Ricinus Communis (Castor) Seed Oil, Rosmarinus Officinalis (Rosemary) Leaf Oil, Argania Spinosa (Argan) Kernel Oil, Tocopherol (Vitamin E).',
    howToUse: 'Apply a few drops directly to scalp and massage gently. Can be used daily or as a hot oil treatment before washing.',
    origin: 'Hair Care Care Line',
    reviews: []
  },
  {
    _id: '650000000000000000000007',
    id: 7,
    name: 'Niacinamide & Zinc Clarifying Cleanser',
    slug: 'niacinamide-zinc-clarifying-cleanser',
    brand: 'GlowLab Skincare',
    category: 'Skincare',
    subcategory: 'Cleansers',
    price: 21.00,
    originalPrice: null,
    rating: 4.7,
    numReviews: 88,
    inStock: true,
    stockCount: 40,
    isBestSeller: false,
    isNewProduct: true,
    image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'A gentle foaming daily gel cleanser with 5% Niacinamide and 1% Zinc PCA to control excess oil, clear pores, and balance skin without tightness.',
    skinType: ['Oily', 'Combination', 'Acne-Prone'],
    ingredients: 'Aqua, Cocamidopropyl Betaine, Niacinamide, Glycerin, Zinc PCA, Salicylic Acid, Sodium Hydroxide, Citric Acid.',
    howToUse: 'Lather a nickel-sized amount with water, massage gently on face for 60 seconds, then rinse with lukewarm water.',
    origin: 'Daily Dermatological Care',
    reviews: []
  },
  {
    _id: '650000000000000000000008',
    id: 8,
    name: 'Sandalwood Beard Care & Grooming Oil',
    slug: 'sandalwood-beard-care-grooming-oil',
    brand: 'Urban Grooming Co.',
    category: 'Grooming',
    subcategory: 'Beard Care',
    price: 24.00,
    originalPrice: 28.00,
    rating: 4.9,
    numReviews: 74,
    inStock: true,
    stockCount: 50,
    isBestSeller: false,
    isNewProduct: true,
    image: 'https://images.unsplash.com/photo-1567928815104-b637ef2dbb71?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1567928815104-b637ef2dbb71?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'A lightweight, non-greasy beard conditioning oil infused with Sandalwood, Jojoba, and Cedarwood to soften facial hair and moisturize skin beneath.',
    skinType: ['All Skin Types'],
    ingredients: 'Simmondsia Chinensis (Jojoba) Seed Oil, Argania Spinosa (Argan) Kernel Oil, Santalum Album (Sandalwood) Oil, Cedrus Atlantica Wood Oil.',
    howToUse: 'Rub 3-5 drops between palms and massage into clean beard and skin underneath daily.',
    origin: 'Men’s Grooming Line',
    reviews: []
  }
];

export const MOCK_EDITORIAL_STORIES = [
  {
    id: 's1',
    title: 'The Ultimate Daily Skincare Routine Guide',
    subtitle: 'Cleansing, hydrating, and sun protection made simple',
    category: 'Skincare Tips',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=1200&auto=format&fit=crop',
    snippet: 'Learn how to layer serums, moisturizers, and sunscreen for radiant, healthy skin in any weather.',
  },
  {
    id: 's2',
    title: 'How to Choose Your Perfect Shade Match',
    subtitle: 'Tips for finding your true foundation undertone',
    category: 'Makeup Guide',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?q=80&w=1200&auto=format&fit=crop',
    snippet: 'Discover simple techniques to identify warm, cool, or neutral undertones for seamless makeup application.',
  },
  {
    id: 's3',
    title: 'Essential Hair Care Secrets for Healthy Length',
    subtitle: 'Nourishing oils and protective styling tips',
    category: 'Hair Care',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80',
    snippet: 'Protect your hair from dryness and breakage with moisture-retaining treatments and scalp care.',
  },
];

export const MOCK_TRUST_ITEMS = [
  {
    id: 't1',
    icon: 'shield-checkmark-outline',
    title: '100% Authentic Products',
    desc: 'Sourced directly from verified brands and official beauty distributors.',
  },
  {
    id: 't2',
    icon: 'airplane-outline',
    title: 'Fast Nationwide Delivery',
    desc: 'Quick, reliable door-to-door shipping across major cities and regions.',
  },
  {
    id: 't3',
    icon: 'card-outline',
    title: 'Secure Payment Options',
    desc: 'Pay safely via Mobile Money (M-Pesa, MoMo, Orange), Credit Cards, or Apple Pay.',
  },
  {
    id: 't4',
    icon: 'sync-outline',
    title: 'Easy Returns & Guarantee',
    desc: 'Hassle-free return policy if you are not completely satisfied.',
  },
  {
    id: 't5',
    icon: 'headset-outline',
    title: 'Dedicated Customer Support',
    desc: 'Friendly beauty support team ready to assist with your order anytime.',
  },
];

export const MOCK_PROMO_BANNERS = [
  {
    id: 1,
    headline: 'Beauty Refresh Sale',
    subtext: 'Get up to 25% off top skincare, makeup & haircare essentials',
    code: 'BEAUTY15',
    badge: 'HOT DEAL',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 2,
    headline: 'New Glam Makeup Collection',
    subtext: 'Explore lipsticks, foundations & eyeshadow palettes',
    code: 'GLAM20',
    badge: 'NEW ARRIVALS',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop',
  }
];
